"""empty message

Revision ID: ea5939d8577a
Revises: 
Create Date: 2021-01-22 10:27:04.146817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea5939d8577a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.drop_index('IDX_93b566d522b73cb8bc46f7405b', table_name='post_categories_category')
    op.drop_index('IDX_a5e63f80ca58e7296d5864bd2d', table_name='post_categories_category')
    op.drop_table('post_categories_category')
    op.drop_table('post')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_9c4e4a89e3674fc9f382d733f03'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_be5fda3aac270b134ff9c21cdee'),
    postgresql_ignore_search_path=False
    )
    op.create_table('post_categories_category',
    sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], name='FK_a5e63f80ca58e7296d5864bd2d3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], name='FK_93b566d522b73cb8bc46f7405bd', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postId', 'categoryId', name='PK_91306c0021c4901c1825ef097ce')
    )
    op.create_index('IDX_a5e63f80ca58e7296d5864bd2d', 'post_categories_category', ['categoryId'], unique=False)
    op.create_index('IDX_93b566d522b73cb8bc46f7405b', 'post_categories_category', ['postId'], unique=False)
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
